export const INDUSTRIES = [

    "Communication/Phone",
    "Computer Related",
    "Product/Service",
    "Construction",
    "Education",
    "Engineering/Architecture",
    "Entertainment",
    "Government",
    "Healthcare",
    "Hospitality",
    "Legal",
    "Insurance",
    "Manufacturing",
    "Market Research",
    "Media/Marketing",
    "Mining",
    "Professional Services",
    "Personal Services",
    "Printing or publishing of computer related industry information",
    "Utilities",
    "Real Estate",
    "Retail",
    "Transportation",
    "Technology/BPO",
    "Wholesale",
    "Tele Communication",
    "Trade Services",
    "Information Technology",
    "Non Profit",
    "Others",
    "Don't Know"

];