# Generated by Django 5.2.14 on 2026-05-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('test_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('live_link', models.URLField(max_length=1000)),
                ('rid_parameter', models.CharField(default='RID', max_length=50)),
                ('our_parameter', models.CharField(default='ID', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('complete_link', models.URLField(max_length=1000)),
                ('terminate_link', models.URLField(max_length=1000)),
                ('quota_full_link', models.URLField(max_length=1000)),
                ('security_terminate_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('target', models.IntegerField(default=0)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loi', models.IntegerField(default=0)),
                ('ir', models.IntegerField(default=0)),
                ('test_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('live_link', models.URLField(max_length=1000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('target', models.IntegerField(default=0)),
                ('complete_link', models.URLField(max_length=1000)),
                ('terminate_link', models.URLField(max_length=1000)),
                ('quota_full_link', models.URLField(max_length=1000)),
                ('security_terminate_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_vendors', to='core.project')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_projects', to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('complete', 'Complete'), ('terminate', 'Terminate'), ('quota_full', 'Quota Full'), ('security_terminate', 'Security Terminate')], default='started', max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=30, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('s2s_status', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondents', to='core.project')),
                ('project_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondents', to='core.projectvendor')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondents', to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RedirectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_type', models.CharField(max_length=50)),
                ('redirect_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_logs', to='core.respondent')),
            ],
        ),
    ]
