# Generated by Django 5.2.14 on 2026-05-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='panel_misc_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respondent',
            name='reconnect_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respondent',
            name='vendor_panelist_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectvendor',
            name='complete_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectvendor',
            name='quota_full_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectvendor',
            name='terminate_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='complete_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quota_full_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='terminate_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
