# Generated by Django 5.2.14 on 2026-05-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_respondent_panel_misc_data_respondent_reconnect_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.AddField(
            model_name='client',
            name='abrv_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='api_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='check_proxy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company_type',
            field=models.CharField(choices=[('client', 'Client'), ('agency', 'Agency'), ('partner', 'Partner')], default='client', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='invoicing_method',
            field=models.CharField(blank=True, choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_diy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('15', '15 Days'), ('30', '30 Days'), ('45', '45 Days'), ('60', '60 Days')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='live_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='test_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
