# Generated by Django 5.2.14 on 2026-05-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_client_company_name_client_abrv_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_type',
            field=models.CharField(choices=[('client', 'Client'), ('internal_company', 'Internal Company'), ('affiliate_partner', 'Affiliates Partner'), ('api_partner', 'API Partner'), ('router_partner', 'Router Partner')], default='client', max_length=50),
        ),
    ]
