# Generated by Django 5.2.14 on 2026-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='invoicing_method',
            field=models.CharField(blank=True, choices=[('monthly_basis', 'Monthly Basis'), ('project_basis', 'Project Basis')], max_length=50, null=True),
        ),
    ]
