# Generated by Django 5.2.14 on 2026-05-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_vendor_contact_person_vendor_abrv_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respondent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='respondent',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respondent',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
