# Generated by Django 5.2.14 on 2026-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_respondent_age_respondent_email_respondent_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_completes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.CharField(default='Self Parent', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reward_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='study_type',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('CATI', 'CATI'), ('Data Processing', 'Data Processing'), ('Doctor', 'Doctor'), ('Focus Group', 'Focus Group'), ('Health care', 'Health care'), ('IDI', 'IDI'), ('IHUT', 'IHUT'), ('In-depth telephone interviews(TDIs)', 'In-depth telephone interviews(TDIs)'), ('Online Board', 'Online Board'), ('Online Community Recruitment', 'Online Community Recruitment'), ('panel build up', 'Panel Build Up'), ('programming', 'Programming'), ('TDI', 'TDI')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='supported_devices',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ir',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='loi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('bidding', 'Bidding'), ('api_staging', 'API Staging'), ('running', 'Running'), ('testing', 'Testing'), ('on_hold', 'On Hold'), ('awaiting_ids', "Awaiting ID's"), ('completed', 'Completed'), ('closed', 'Closed')], default='bidding', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='test_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
