# Generated by Django 5.2.14 on 2026-05-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_client_contact_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvendor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=50),
        ),
    ]
