# Generated by Django 5.2.14 on 2026-05-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_projectvendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvendor',
            name='ask_age',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectvendor',
            name='ask_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectvendor',
            name='ask_gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectvendor',
            name='ask_zip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectvendor',
            name='max_redirects',
            field=models.IntegerField(default=99999),
        ),
        migrations.AddField(
            model_name='projectvendor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectvendor',
            name='qualification_required',
            field=models.BooleanField(default=True),
        ),
    ]
