# Generated by Django 5.2.14 on 2026-06-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_projectvendor_ask_age_projectvendor_ask_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvendor',
            name='s2s_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
