# Generated by Django 5.2.14 on 2026-06-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_panelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='detected_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
