# Generated by Django 5.2.14 on 2026-06-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvendor',
            name='gid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectvendor',
            name='supplier_parameter_template',
            field=models.CharField(default='pid={{PANELIST IDENTIFIER}}&ext={{PANEL MISC DATA}}&reconnectID={{RECONNECTID}}', max_length=500),
        ),
    ]
