# Generated by Django 5.2.14 on 2026-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_respondent_termination_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='proxy_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respondent',
            name='vpn_detected',
            field=models.BooleanField(default=False),
        ),
    ]
