# Generated by Django 5.2.14 on 2026-07-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_respondent_proxy_detected_respondent_vpn_detected'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('radio', 'Radio'), ('checkbox', 'Checkbox'), ('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('select', 'Dropdown')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_questions', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.screeningquestion')),
            ],
        ),
        migrations.CreateModel(
            name='RespondentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.respondent')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.screeningquestion')),
            ],
        ),
    ]
