# Generated by Django 5.2.14 on 2026-07-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_screeningquestion_screeningoption_respondentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screening_pass_percentage',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='respondent',
            name='screening_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='respondent',
            name='screening_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
