# Generated by Django 5.2.14 on 2026-07-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_project_screening_pass_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_screening',
            field=models.BooleanField(default=False),
        ),
    ]
