# Generated by Django 5.2.14 on 2026-07-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_project_enable_screening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectvendor',
            name='qualification_required',
        ),
    ]
