# Generated by Django 5.2.14 on 2026-07-15 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_respondentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='panelist',
            name='last_synced',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='panelist',
            name='source',
            field=models.CharField(default='Opinion Bunch', max_length=30),
        ),
        migrations.CreateModel(
            name='PanelCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('target', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_campaigns', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='PanelCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_token', models.CharField(max_length=100, unique=True)),
                ('survey_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('opened', 'Opened'), ('started', 'Started'), ('complete', 'Complete'), ('terminate', 'Terminate'), ('quota_full', 'Quota Full')], default='pending', max_length=30)),
                ('email_sent', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.panelcampaign')),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.panelist')),
            ],
        ),
    ]
