# Generated by Django 5.2.14 on 2026-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_panelist_is_active_panelist_last_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelcampaign',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='panelcampaign',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='panelcampaign',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
