# Generated by Django 5.2.14 on 2026-07-16 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_panelcampaign_country_panelcampaign_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelcampaignrecipient',
            name='respondent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.respondent'),
        ),
    ]
