# Generated by Django 5.2.14 on 2026-07-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_panelcampaignrecipient_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelcampaign',
            name='project_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel_campaigns', to='core.projectvendor'),
        ),
        migrations.AlterField(
            model_name='panelcampaign',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
