# Generated by Django 5.2.14 on 2026-07-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_panelcampaign_project_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelcampaign',
            name='country',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='panelcampaign',
            name='industry',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
