# Generated by Django 5.2.14 on 2026-07-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_panelcampaign_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelcampaignrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('opened', 'Opened'), ('started', 'Started'), ('complete', 'Complete'), ('terminate', 'Terminate'), ('quota_full', 'Quota Full'), ('security_terminate', 'Security Terminate')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='CampaignEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Survey Invitation', max_length=255)),
                ('body', models.TextField(default='\n    Hello {{first_name}},\n\n    You have been invited to participate in our survey.\n\n    Survey Link:\n    {{survey_link}}\n\n    Thank you.\n\n    Opinion Bunch\n    ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_template', to='core.panelcampaign')),
            ],
            options={
                'ordering': ['campaign'],
            },
        ),
    ]
