# Generated by Django 5.2.14 on 2026-07-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_panelcampaignrecipient_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelist',
            name='optin_type',
            field=models.CharField(default='SOI', max_length=10),
        ),
        migrations.AddField(
            model_name='panelist',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
