# Generated by Django 5.2.14 on 2026-07-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_panelist_email_verified_panelist_optin_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='completed_surveys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panelist',
            name='last_survey_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panelist',
            name='quota_full_surveys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panelist',
            name='security_terminated_surveys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panelist',
            name='terminated_surveys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panelist',
            name='total_surveys',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
