# Generated by Django 5.2.14 on 2026-09-10 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_panelist_completed_surveys_panelist_last_survey_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='respondent',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondents', to='core.participant'),
        ),
        migrations.AddConstraint(
            model_name='respondent',
            constraint=models.UniqueConstraint(condition=models.Q(('participant__isnull', False)), fields=('participant', 'project'), name='unique_participant_per_project'),
        ),
    ]
